# Utiliser une image Python officielle avec la version souhaitée
FROM python:3.12-slim

# Installer git et les outils nécessaires pour la compilation
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    make \
    gcc \
    pkg-config \
    #theano \
    #libblas-dev \
    build-essential \
    g++ \
    libopenblas-dev \
    liblapack-dev \
    libhdf5-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Définir le répertoire de travail
WORKDIR /app

# Copier les scripts de l'application dans le conteneur
COPY scripts /app/scripts

# Installer les dépendances Python via pip
RUN pip install --no-cache-dir \
    pymc==5.13.0 \
    openblas \
    psutil \
    numpy \
    dash==2.16.1 \
    dash_cytoscape==0.3.0 \
    flask==3.0.3 \
    pandas==2.2.1 \
    arviz==0.18.0 \
    networkx==3.3

# Exposer le port sur lequel Dash va tourner
EXPOSE 8080

# Commande pour lancer l'application
CMD ["python", "scripts/app.py"]
