
FROM mambaorg/micromamba:1.5.9

LABEL name="pymc"
LABEL description="Environment for PyMC version 4"

ENV MAMBA_DOCKERFILE_ACTIVATE=1
ENV ENV_NAME=dash-app
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

# Switch to jovyan to avoid container runs as root
USER $NB_UID

#RUN mkdir -p /app
COPY environment.yml /tmp/environment.yml
COPY scripts /app/scripts
# RUN mamba env create -f /tmp/environment.yml && \
#     /bin/bash -c ". activate dash-app && \
#     mamba install -c conda-forge -y pymc" && \
#     conda clean --all -f -y

ENV PATH=/opt/conda/envs/dash-app/bin:$PATH

RUN mamba env create -f /tmp/environment.yml && \
    mamba run -n dash-app mamba install -c conda-forge -y pymc && \
    mamba clean --all -f -y

# Fix PkgResourcesDeprecationWarning
RUN pip install --upgrade --user setuptools==58.3.0

#Setup working folder
WORKDIR /app

# For running from bash
SHELL ["/bin/bash","-c"]
RUN echo "conda activate dash-app" >> ~/.bashrc && \
    source ~/.bashrc

# For running from jupyter notebook
EXPOSE 8080
CMD ["conda", "run", "--no-capture-output", "-n", "dash-app", "python", "scripts/app.py"]
