FROM mambaorg/micromamba:1.5.9

# Définir les variables d'environnement
#ENV MAMBA_DOCKERFILE_ACTIVATE=1
#ENV ENV_NAME=dash_app

#RUN apt-get update && apt-get upgrade -y && apt-get install -y git

#RUN mamba create -n $ENV_NAME -y python=3.12.2 pymc==5.13.0 -c conda-forge 



# Créer et activer un nouvel environnement avec mamba
RUN micromamba create -n dash_app python=3.12.2 pymc==5.13.0 -c conda-forge -y && \
    micromamba clean --all -f -y

USER root

RUN mkdir -p /app
#RUN mkdir -p /app && chown -R micromamba /app

#USER micromamba

# Changer le shell pour utiliser l'environnement conda
#SHELL ["conda", "run", "-n", "dash_app", "/bin/bash", "-c"]
SHELL ["conda", "run", "-n", "dash_app", "/bin/bash", "-c"]

#
COPY environment.yml /tmp/environment.yml
COPY scripts /app/scripts

# Installer les dépendances avec mamba
#RUN micromamba env update -n dash_app -f /tmp/environment.yml

RUN micromamba env create -n dash_app -f /tmp/environment.yml && \
    micromamba clean --all --yes

# Activer l'environnement conda
RUN echo "conda activate dash_app" >> ~/.bashrc
SHELL ["conda", "run", "-n", "dash_app", "/bin/bash", "-c"]

# Exposer le port sur lequel Dash va tourner
EXPOSE 8080

WORKDIR /app

# Commande pour lancer l'application
CMD ["conda", "run", "--no-capture-output", "-n", "dash_app", "python", "scripts/app.py"]