name: dash-app
channels:
- conda-forge
- defaults
dependencies:
# Base dependencies
- blas
- cachetools>=4.2.1
- cloudpickle
- h5py>=2.7
- numpy>=1.15.0
- pip
- psutil
- pytensor>=2.25.1,<2.26
- python-graphviz
- networkx
- scipy>=1.4.1
- typing-extensions>=3.7.4
- threadpoolctl>=3.1.0
- pip:
      - dash==2.16.1
      - dash_cytoscape==0.3.0
      - flask==3.0.3 
      - pandas==2.2.1 
      - arviz==0.18.0
      