name: pymc_env
channels:
  - conda-forge
dependencies:
  - python=3.12.2
  - pymc==5.13.0
  - psutil
  - pip:
      - dash==2.16.1
      - dash_cytoscape==0.3.0
      - flask==3.0.3 
      - pandas==2.2.1 
      - arviz==0.18.0
      - numpy==1.26.4